apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
  # namespace: kafka-kraft
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
  # namespace: kafka-kraft
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 19092
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_LISTENERS
              value: BROKER://:9092,LISTENER_LOCAL://:19092,CONTROLLER://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: BROKER://$(HOSTNAME).kafka-svc.default.svc.cluster.local:9092,LISTENER_LOCAL://localhost:19092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: BROKER:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: BROKER
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '3'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '0@kafka-0.kafka-svc.default.svc.cluster.local:9093,1@kafka-1.kafka-svc.default.svc.cluster.local:9093,2@kafka-2.kafka-svc.default.svc.cluster.local:9093'
            - name: CLUSTER_ID
              value: 'MkU3OEVBNTcwNTJENDM2Qk'
            - name: KAFKA_COMPRESSION_TYPE
              value: producer
            - name: KAFKA_PROCESS_ROLES
              value: 'controller,broker'
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: TOPIC_AUTO_CREATE
              value: 'true'
          resources:
            limits:
              cpu: '500m'
