apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: default
  labels:
    app: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-service
          image: fos/payment-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://postgres-service:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified'
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: 'kafka-svc:9092'
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: 'http://schema-registry-service:8081'
          resources:
            limits:
              memory: '1024Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  selector:
    app: payment-deployment
  ports:
    - name: payment-service-port
      protocol: TCP
      port: 80
      targetPort: 8182
  type: LoadBalancer
  loadBalancerIP: ''
