---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: 'admin'
          resources:
            limits:
              memory: '1024Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  labels:
    app: postgres-deployment
spec:
  selector:
    app: postgres-deployment
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
  loadBalancerIP: ''
